# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-master

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v14.18.1'        
        cache: 'yarn'
    - run: yarn
      
    # Commits all changed files to the repository
    - name: Config Repo
      run: |
        git config --global user.name "codeeshop-oc/quasar-tel-input"
        git config --global user.email "github-stats[bot]@codeeshop-oc.github.io"
    - name: Deleting Previous Branches
      run: |
        git branch -D dist-files || echo
        git push -d origin dist-files || echo
    - name: Continue Committing
      run: |            
        git checkout -b dist-files
        git stash
        git rebase master dist-files
    - name: Yarn Building
      run: |            
        yarn build
    - name: Continue Committing
      run: |
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update Dist Files' || echo
        git push -u origin dist-files
        git checkout master
        gh repo set-default codeeshop-oc/quasar-tel-input
        gh pr create --base master --head dist-files --title "Update Build Files" --body "Dist-Build Files" --reviewer codeeshop-oc  || echo
        gh pr merge dist-files -m --auto || echo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
