# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-master

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v14.18.1'        
        cache: 'yarn'
    - run: yarn
    - name: Building
      run: yarn build
      
    # Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "Anant"
        git config --global user.email "anantnegi8@gmail.com"          
        git checkout -b dist-files
        git fetch
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update Dist Files' || echo
        git push -u origin dist-files
        gh pr create --base master --head dist-files --title "Update Build Files" --body "Dist-Build Files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
